# Generated by Django 6.0.7 on 2026-08-05 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentComplex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Apartment complex',
                'verbose_name_plural': 'Apartment complexes',
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_no', models.CharField(max_length=50)),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apartments', to='billing.apartmentcomplex')),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentResident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='residency_history', to='billing.apartment')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveSmallIntegerField()),
                ('period_month', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='billing.apartmentcomplex')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_approval_decisions', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_approval_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveSmallIntegerField()),
                ('period_month', models.PositiveSmallIntegerField()),
                ('window_start_date', models.DateField()),
                ('window_end_date', models.DateField()),
                ('total_bill', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_fixed_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_consumption_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_energy', models.DecimalField(decimal_places=4, max_digits=18)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_runs', to='billing.apartmentcomplex')),
                ('run_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='MeterDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modbus_address', models.CharField(max_length=100)),
                ('installed_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meter_devices', to='billing.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_value', models.DecimalField(decimal_places=4, help_text='Kümülatif enerji (Wh)', max_digits=18)),
                ('read_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='billing.meterdevice')),
            ],
            options={
                'ordering': ['read_at'],
            },
        ),
        migrations.CreateModel(
            name='ApartmentBillingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_consumed', models.DecimalField(decimal_places=4, max_digits=18)),
                ('area_ratio', models.DecimalField(decimal_places=6, max_digits=12)),
                ('energy_ratio', models.DecimalField(decimal_places=6, max_digits=12)),
                ('fixed_share', models.DecimalField(decimal_places=2, max_digits=14)),
                ('consumption_share', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_payable', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('anomaly', 'Anomaly')], default='normal', max_length=20)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_lines', to='billing.apartment')),
                ('billing_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='billing.billingrun')),
                ('end_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_lines_as_end', to='billing.meterreading')),
                ('start_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_lines_as_start', to='billing.meterreading')),
            ],
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['complex', 'is_active'], name='billing_apa_complex_aa79da_idx'),
        ),
        migrations.AddConstraint(
            model_name='apartment',
            constraint=models.UniqueConstraint(fields=('complex', 'unit_no'), name='uniq_apartment_unit_per_complex'),
        ),
        migrations.AddIndex(
            model_name='apartmentresident',
            index=models.Index(fields=['apartment', '-started_at'], name='billing_apa_apartme_0cc498_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['complex', 'period_year', 'period_month', 'status'], name='billing_app_complex_888bf3_idx'),
        ),
        migrations.AddIndex(
            model_name='billingrun',
            index=models.Index(fields=['complex', 'period_year', 'period_month'], name='billing_bil_complex_87af83_idx'),
        ),
        migrations.AddIndex(
            model_name='meterdevice',
            index=models.Index(fields=['apartment', 'is_active'], name='billing_met_apartme_bbf342_idx'),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['device', 'read_at'], name='billing_met_device__77d34d_idx'),
        ),
        migrations.AddIndex(
            model_name='apartmentbillingline',
            index=models.Index(fields=['apartment', 'billing_run'], name='billing_apa_apartme_5d8665_idx'),
        ),
    ]
