# Generated by Django 6.0.7 on 2026-08-05 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='billingrun',
            index=models.Index(fields=['complex', 'window_start_date', 'window_end_date'], name='billing_bil_complex_377342_idx'),
        ),
    ]
