# Generated by Django 6.0.7 on 2026-08-05 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_billingrun_billing_bil_complex_377342_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentresident',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residency_history', to='billing.apartment'),
        ),
    ]
