# Generated by Django 6.0.7 on 2026-08-05 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_apartmentresident_apartment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplexAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='billing.apartmentcomplex')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complex_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='billing_com_user_id_53ca6c_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'complex'), name='uniq_complexaccess_user_complex')],
            },
        ),
    ]
