# Generated by Django 6.0.7 on 2026-08-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_complexaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentbillingline',
            name='end_energy_value',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Bu satırın tüketiminin hesaplandığı bitiş (son) kümülatif enerji endeksi. Modbus okuması varsa `end_reading.raw_value` ile aynıdır; manuel girişte kullanıcının panelden girdiği 'Son Enerji' değeridir. Hiçbiri yoksa `null`.", max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='apartmentbillingline',
            name='start_energy_value',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Bu satırın tüketiminin hesaplandığı başlangıç (ilk) kümülatif enerji endeksi. Modbus okuması varsa `start_reading.raw_value` ile aynıdır; manuel girişte kullanıcının panelden girdiği 'İlk Enerji' değeridir. Hiçbiri yoksa `null`.", max_digits=18, null=True),
        ),
    ]
