# Generated by Django 6.0.7 on 2026-08-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_apartmentbillingline_end_energy_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='block',
            field=models.CharField(blank=True, default='', help_text="Blok/etap adı (opsiyonel) — örn. 'A Blok'. Toplu Excel özetinde (bkz. invoice_pdf.excel) ayrı bir sütun olarak gösterilir.", max_length=50),
        ),
    ]
