# Generated by Django 6.0.7 on 2026-08-06 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_apartment_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='reference_consumption_enabled',
            field=models.BooleanField(default=False, help_text="15°C Referans Tüketim Düzeltmesi bu dairede uygulansın mı? Sadece 'Evet' ise ve bir Referans Tüketim Değeri girilmişse faturalandırmada kullanılır."),
        ),
        migrations.AddField(
            model_name='apartment',
            name='reference_consumption_value',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Referans Tüketim Değeri. Şu an admin panelinden elle girilir (ileride hesaplama/Excel/dış sistem kaynaklı olabilir — bkz. billing.reference_consumption.ReferenceConsumptionSetting.source).', max_digits=18, null=True),
        ),
        migrations.CreateModel(
            name='ApartmentBillingLineCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_enabled', models.BooleanField(default=False, help_text='Faturalandırma anında bu daire için düzeltme etkin miydi (snapshot).')),
                ('reference_value', models.DecimalField(blank=True, decimal_places=4, help_text='Faturalandırma anındaki Referans Tüketim Değeri (snapshot).', max_digits=18, null=True)),
                ('reference_source', models.CharField(choices=[('manual', 'Manuel (Admin)')], default='manual', max_length=20)),
                ('corrected_energy_consumed', models.DecimalField(decimal_places=4, help_text='max(gerçek tüketim, referans tüketim) — düzeltme etkin/uygulanmadıysa gerçek tüketimle (ApartmentBillingLine.energy_consumed) aynıdır.', max_digits=18)),
                ('corrected_consumption_share', models.DecimalField(decimal_places=2, help_text='Düzeltilmiş Tüketim Payı (TL).', max_digits=14)),
                ('correction_amount', models.DecimalField(decimal_places=2, help_text="15°C Referans Tüketim Düzeltmesi (TL) = Düzeltilmiş Tüketim Payı - Tüketim Gider Payı. Düzeltme uygulanmadıysa/etkisi olmadıysa 0,00'dır.", max_digits=14)),
                ('corrected_total_payable', models.DecimalField(decimal_places=2, help_text='Nihai Ödenecek Tutar (TL) = Sabit Gider Payı + Düzeltilmiş Tüketim Payı.', max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billing_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reference_correction', to='billing.apartmentbillingline')),
            ],
            options={
                'verbose_name': '15°C referans tüketim düzeltmesi',
                'verbose_name_plural': '15°C referans tüketim düzeltmeleri',
            },
        ),
    ]
