# Generated by Django 6.0.7 on 2026-08-06 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_apartment_reference_consumption_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='billing_run',
            field=models.OneToOneField(blank=True, help_text='Bu onay kullanılarak başarıyla oluşturulan yeniden hesaplama. Boşsa onay henüz tüketilmemiştir.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_request', to='billing.billingrun'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='window_end_date',
            field=models.DateField(blank=True, help_text='Yeniden hesaplama talebinin bitiş tarihi. Özellik eklenmeden önceki eski taleplerde boş olabilir.', null=True),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='window_start_date',
            field=models.DateField(blank=True, help_text='Yeniden hesaplama talebinin başlangıç tarihi. Özellik eklenmeden önceki eski taleplerde boş olabilir.', null=True),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['complex', 'window_start_date', 'window_end_date', 'status'], name='billing_app_complex_8aca50_idx'),
        ),
    ]
