# Generated by Django 6.0.7 on 2026-08-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_approvalrequest_billing_run_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='reference_consumption_enabled',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='reference_consumption_value',
        ),
        migrations.DeleteModel(
            name='ApartmentBillingLineCorrection',
        ),
    ]
