# Generated by Django 6.0.7 on 2026-08-06 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_remove_apartment_reference_consumption_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('warning', 'Uyarı'), ('critical', 'Kritik')], max_length=20)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MeterReadingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(db_index=True)),
                ('energy_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('success', 'Başarılı'), ('failed', 'Başarısız'), ('recovered', 'Sorun Çözüldü')], db_index=True, max_length=20)),
                ('retry_number', models.PositiveIntegerField(default=0)),
                ('error_type', models.CharField(blank=True, choices=[('timeout', 'Timeout'), ('connection_error', 'Connection Error'), ('modbus_exception', 'Modbus Exception'), ('invalid_data', 'Geçersiz Veri'), ('unexpected_response', 'Beklenmeyen Cevap'), ('unexpected_error', 'Beklenmeyen Hata')], default='', max_length=40)),
                ('error_description', models.TextField(blank=True, default='')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('device_identifier', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Sayaç okuma geçmişi',
                'verbose_name_plural': 'Sayaç okuma geçmişi',
                'ordering': ['-read_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='meterdevice',
            name='consecutive_failures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meterdevice',
            name='failure_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meterdevice',
            name='faulty_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meterdevice',
            name='faulty_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meterdevice',
            name='last_error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='meterdevice',
            name='last_error_type',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='meterdevice',
            name='last_failure_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meterdevice',
            name='last_success_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meterdevice',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='meterdevice',
            name='status',
            field=models.CharField(choices=[('normal', 'Normal'), ('retrying', 'Retry Devam Ediyor'), ('faulty', 'Arızalı / Veri Alınamıyor'), ('waiting', 'Bekleniyor')], db_index=True, default='waiting', max_length=20),
        ),
        migrations.AddField(
            model_name='meterdevice',
            name='total_retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='meterdevice',
            index=models.Index(fields=['is_active', 'status', 'next_retry_at'], name='billing_met_is_acti_de8975_idx'),
        ),
        migrations.AddField(
            model_name='meteralert',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='billing.meterdevice'),
        ),
        migrations.AddField(
            model_name='meterreadinglog',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meter_reading_history', to='billing.apartment'),
        ),
        migrations.AddField(
            model_name='meterreadinglog',
            name='complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meter_reading_history', to='billing.apartmentcomplex'),
        ),
        migrations.AddField(
            model_name='meterreadinglog',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reading_history', to='billing.meterdevice'),
        ),
        migrations.AddIndex(
            model_name='meteralert',
            index=models.Index(fields=['is_active', 'severity', '-updated_at'], name='billing_met_is_acti_300cb7_idx'),
        ),
        migrations.AddConstraint(
            model_name='meteralert',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('device',), name='uniq_active_meter_alert_per_device'),
        ),
        migrations.AddIndex(
            model_name='meterreadinglog',
            index=models.Index(fields=['complex', '-read_at'], name='billing_met_complex_8c2261_idx'),
        ),
        migrations.AddIndex(
            model_name='meterreadinglog',
            index=models.Index(fields=['status', '-read_at'], name='billing_met_status_a44e91_idx'),
        ),
        migrations.AddIndex(
            model_name='meterreadinglog',
            index=models.Index(fields=['device', '-read_at'], name='billing_met_device__67adfc_idx'),
        ),
    ]
