# Generated by Django 6.0.7 on 2026-08-07 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_meteralert_meterreadinglog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentcomplex',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='apartmentcomplex',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soft_deleted_complexes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apartmentcomplex',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
