"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Tüm ortam-bağımlı ayarlar (secret, DB kimlik bilgileri, debug, host
# listesi) `.env` dosyasından okunur; kod içinde gizli bilgi TUTULMAZ.
# `.env` repo'ya gitmez (bkz. .gitignore); yerel/Docker geliştirme için
# gerçek değerlerle, sunucuda ise o ortama özel değerlerle doldurulur —
# production'a taşırken bu dosya dışında hiçbir şey değişmez.
env = environ.Env(
    DEBUG=(bool, False),
)
environ.Env.read_env(BASE_DIR / ".env")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_bootstrap5',

'accounts',
'dashboard',
'billing',
'audit.apps.AuditConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Nginx henüz devrede değilken (ve nginx devredeyken de zararsız bir
    # yedek olarak) static dosyaları doğrudan Django/gunicorn'dan servis
    # eder — `DEBUG=False` olduğunda Django'nun kendisi static dosya
    # sunmadığı için bu olmadan production'da admin paneli/CSS bozuk açılır.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'audit.middleware.AuditExceptionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

# CSRF token bir sekmede giriş/çıkış yapılınca yenilenebildiği için (bkz.
# django.contrib.auth.login -> rotate_token), başka bir sekmede/pencerede
# uzun süredir açık kalmış bir form gönderildiğinde Django'nun teknik CSRF
# hata sayfası yerine kullanıcıyı dostane bir mesajla giriş ekranına geri
# yönlendiriyoruz (bkz. accounts.views.csrf_failure_view).
CSRF_FAILURE_VIEW = 'accounts.views.csrf_failure_view'

# Nginx/başka bir reverse proxy arkasında, kendi domain'inden gelen
# formları CSRF açısından güvenilir saymak için (bkz. Django CSRF_TRUSTED_ORIGINS
# dokümantasyonu — Django 4+'te reverse-proxy senaryolarında zorunlu).
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])

# `DEBUG=False` (production) olduğunda otomatik devreye giren güvenlik
# ayarları — ayrı bir env değişkenine gerek yok, mantıksal olarak DEBUG'a
# bağlı: yerel/Docker geliştirmede DEBUG=True olduğundan bunlar kapalı
# kalır (aksi halde düz HTTP üzerinden geliştirme yapılamaz).
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = not DEBUG

# Nginx/Render/Railway gibi bir reverse proxy SSL'i kendi üzerinde
# sonlandırıp Django'ya düz HTTP ile iletir; bu header olmadan
# `SECURE_SSL_REDIRECT=True` sonsuz yönlendirme döngüsüne yol açar.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env("DATABASE_NAME"),
        'USER': env("DATABASE_USER"),
        'PASSWORD': env("DATABASE_PASSWORD"),
        'HOST': env("DATABASE_HOST"),
        'PORT': env("DATABASE_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'tr'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# `collectstatic`'in topladığı dosyaların yazıldığı klasör — Docker
# imajında/production'da gunicorn+WhiteNoise (veya ileride nginx) buradan
# servis eder. Git'e girmez (bkz. .gitignore).
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# `invoice_pdf` modülünün ürettiği daire bazlı PDF Gider Bildirimlerinin
# yazıldığı kök klasör (bkz. invoice_pdf/service.py). Alt klasörler
# `<yıl>/<ay>/` şeklinde otomatik oluşturulur. Bu klasör public/static
# olarak SUNULMAZ — dosyalar yalnızca `dashboard` view'ları üzerinden,
# erişim yetkisi kontrol edildikten sonra indirilir.
GENERATED_INVOICES_DIR = BASE_DIR / "generated_invoices"
