# Generated by Django 6.0.7 on 2026-08-06 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('user_role', models.CharField(blank=True, max_length=30)),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('category', models.CharField(choices=[('authentication', 'Kimlik Doğrulama'), ('user', 'Kullanıcı'), ('complex', 'Bina'), ('apartment', 'Daire'), ('billing', 'Faturalandırma'), ('system', 'Sistem')], db_index=True, max_length=30)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('success', models.BooleanField(db_index=True, default=True)),
                ('object_type', models.CharField(blank=True, max_length=80)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sistem logu',
                'verbose_name_plural': 'Sistem logları',
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['category', '-occurred_at'], name='audit_audit_categor_ba486e_idx'), models.Index(fields=['user', '-occurred_at'], name='audit_audit_user_id_8cae69_idx'), models.Index(fields=['success', '-occurred_at'], name='audit_audit_success_212188_idx'), models.Index(fields=['archived_at', '-occurred_at'], name='audit_audit_archive_0e07f7_idx')],
            },
        ),
    ]
